### ISSUE TITLE
请问支持列表滚动到底部，自动调起bottom_sheet吗

### ISSUE THREAD

**Issue by jahnli** [dbenitez-bcn/solid_bottom_sheet#11]
请问支持列表滚动到底部，自动调起bottom_sheet吗
![image](https://user-images.githubusercontent.com/20943608/66632218-854a2d00-ec3a-11e9-96cc-40c7747fd149.png)

拉到底部 自动tanqi弹起bottom_sheet

类似于豆瓣电影或者抖音

**Comment by dbenitez-bcn** [comment]
Could you please write this issue in english? Thanks for the support.

**Comment by jahnli** [comment]
Please support The list scrolls to the bottom    Automatic bottom sheet

**Comment by jahnli** [comment]
Automatically tanqi the bottom sheet      Similar to douban movies or douyin

**Comment by dbenitez-bcn** [comment]
I can add two properties: onHide and onShow that will be two functions that will be executed when the solid bottom sheet is completely hided or completely shown.

**Comment by jahnli** [comment]
> 我可以添加两个属性：onHide和onShow，这两个函数将在完全隐藏或完全显示实体底页时执行。

Thank you very much. When do you plan to join them

**Comment by dbenitez-bcn** [comment]
As soon as possible. I'm currently working on adding UI testing. After increasing the test coverage I will start adding new feature to the package.

**Comment by jahnli** [comment]
> 尽快地。我目前正在添加UI测试。在增加测试覆盖率之后，我将开始向软件包中添加新功能。

Ok, would you consider supporting this effect in the future

!( http://cdn.jahnli.cn/movie_top_week_praise1.gif?imageslim)

**Comment by dbenitez-bcn** [comment]
This effect is quite difficult to do. For the moment it's not in my plans, sorry.

**Comment by jahnli** [comment]
> This effect is quite difficult to do. For the moment it's not in my plans, sorry.

Ok thank you

**Comment by dbenitez-bcn** [comment]
OnShow and onHide callbacks will be added on the next version 0.1.7 . Update your dependencies when update is available. If every thing goes fine I will be publishing new version today. I will close this issue when new version is available.

**Comment by jahnli** [comment]
Well, thank you and I'll be looking forward to it



| |
hanson_li
|
|
hanson_li@amaxchina.com
|
签名由网易邮箱大师定制
在2019年10月28日 00:15，David Benitez<notifications@github.com> 写道：

OnShow and onHide callbacks will be added on the next version 0.1.7 . Update your dependencies when update is available. If every thing goes fine I will be publishing new version today. I will close this issue when new version is available.

**Comment by dbenitez-bcn** [comment]
Version 0.1.7 released right now! Check if the new callbacks works for you.
If you like this package don't forget to start it ★. Thank you for your support with this issue!
