### ISSUE TITLE
Bottomsheet close

### ISSUE THREAD

**Issue by Ionys320** [dbenitez-bcn/solid_bottom_sheet#17]
Hello,
The bottomsheet close automatically when I click on a button inside of a ListView. Why ?

**Comment by dbenitez-bcn** [comment]
Could you please share your code? All the scaffold if its posible. Ty

**Comment by Ionys320** [comment]
I can share you all the code. But I resolved the problem by remove the SolidBottomSheet of the bottomScheet scaffold property and putting it as a normal widget.
