### ISSUE TITLE
Hot reload close the bottom sheet

### ISSUE THREAD

**Issue by Ionys320** [dbenitez-bcn/solid_bottom_sheet#18]
Hello,
Flutter's hot reload automatically close the bottom sheet.

Could you do something ?

**Comment by dbenitez-bcn** [comment]
I can have a look but I think that its related on how hot reload works by itself

**Comment by Ionys320** [comment]
And I don't know why, but sometimes (maybe because there is a setState in my buttons), the bottom sheet closes.

**Comment by dbenitez-bcn** [comment]
Maybe thats the issue. Try to save the isOpen state on your widget but anyways I will try to store this state inside Solid Bottom Sheet.

**Comment by dbenitez-bcn** [comment]
But its not a big issue because I thinks that this is just going to apprear when user navigates to an other screen so its not a production problem.
