### ISSUE TITLE
Question: how to set border radius, and change opacity if possible?

### ISSUE THREAD

**Issue by themisir** [dbenitez-bcn/solid_bottom_sheet#19]
Hi,

I wanted to change border-radius using `BoxDecorator` but the result is not fine. The borders were clipped but I saw white background bellow borders. (my background is colorful so I want opaque bg not white).

Also, I wanted to change the opacity of the container but changing the color of `Container` or adding `Opacity` above container did not work.

Thanks in advance!

**Comment by themisir** [comment]
Fixed by adding `canvasColor: Colors.transparent,` and using Stack.

**Comment by MarkStepp** [comment]
@TheMisir - can you show an example

**Comment by themisir** [comment]
@MarkStepp I don't remember actually, but I think I changed child container's `borderRadius` property. I'm sorry but I forget where did I write the code.

It looked like that:

```dart
Stack(
  children: [
    YourScreenContent(),
    SolidBottomSheet(
      headerBar: Container(
        decoration: new BoxDecoration(
          color: Colors.green, 
          borderRadius: new BorderRadius.only(
            topLeft:  const  Radius.circular(40.0),
            topRight: const  Radius.circular(40.0))
          ),
      ),
    ),
  ],
);
```

**Comment by blackmenthor** [comment]
If anyone's wondering, the `canvasColor` is supposed to be used inside your `MaterialApp`'s `ThemeData`
