### ISSUE TITLE
BottomSheet is closing on setState

### ISSUE THREAD

**Issue by gabrielCuringa** [dbenitez-bcn/solid_bottom_sheet#20]
The component closes instantly when the setState function is called.

**Comment by dbenitez-bcn** [comment]
Yes you are right. This is a known issue. I'm working on it.

**Comment by athul-ain** [comment]
Same issue here,

Please fix it as soon as possible

**Comment by 3rsin3rgul** [comment]
Hello,
Is there any news about it?

**Comment by herarya** [comment]
hi any updates?

**Comment by dbenitez-bcn** [comment]
Still working on this. But no solution found for the moment...

**Comment by nxcco** [comment]
Any guess what's the reason for that?

**Comment by Rehckover** [comment]
![image](https://user-images.githubusercontent.com/28598744/85213310-5194da80-b365-11ea-87c4-338f995fb1c1.png)
After set state is called opened value is overridden by default showOnAppear

**Comment by LCostaN** [comment]
Please try like this. it's working for me
'''
bool _showOnAppear = false;
 
@override
  Widget build(BuildContext context) {
    return SlideTransition(
        position: _offsetAnimation,
        child: SolidBottomSheet(
          showOnAppear: _showOnAppear,
          controller: _bottomSheetController,
          headerBar: headerWidget(),
          body: Container(),
          onHide: () => _showOnAppear = false,
          onShow: () => _showOnAppear = true,
        )
    );
  }
'''

**Comment by JelleScheer** [comment]
@LCostaN doesn't seem to work for me, sadly.
@dbenitez-bcn any news? :)

**Comment by hemang249** [comment]
This is pretty old, but in case if someone is still stuck with this issue, separating out the state handling to a separate Stateful Widget worked for me. 

In my case I had a form inside the BottomSheet, So i just separated out the form portion and its state as a separate Widget and its working fine now.

**This isn't a fix but a workaround for the problem.**
