### ISSUE TITLE
Іs this plugin still supported?

### ISSUE THREAD

**Issue by xarmatura** [dbenitez-bcn/solid_bottom_sheet#31]
I want to know, because there are some exceptions from the library that have not been fixed @dbenitez-bcn

**Comment by dbenitez-bcn** [comment]
Right now I'm focused in other projects so I can't spend the time this package deserve. But I also know that there is a bunch of other packages that does the same and even better. I encourage you to check them out.

**Comment by mziadd** [comment]
> Right now I'm focused in other projects so I can't spend the time this package deserve. But I also know that there is a bunch of other packages that does the same and even better. I encourage you to check them out.

Hi, can you name these packges please

**Comment by dbenitez-bcn** [comment]
What do you mean by name the package?

**Comment by mziadd** [comment]
i mean to list the packages
