### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by caesar3x** [dbenitez-bcn/solid_bottom_sheet#32]
Hello,

Thank you for great module.

Could you please let me know how to add null-safety supoprt for this module?

Thanks.

**Comment by dbenitez-bcn** [comment]
It is already (https://github.com/dbenitez-bcn/solid_bottom_sheet/pull/30) but I haven't have the chance to upload it to pub.dev . Will do it during the day. 
Thanks for your interest

**Comment by dbenitez-bcn** [comment]
Update to version 0.1.10 and let me know if now supports null-safety

**Comment by caesar3x** [comment]
Look like it is working fine.
Thank you very much!
