### ISSUE TITLE
Usage of Solid Bottom Sheet 

### ISSUE THREAD

**Issue by mookypoo** [dbenitez-bcn/solid_bottom_sheet#35]
Hi developers,

I've been looking for a way to contact you guys via email, but have failed to do so - so I'll be leaving an "issue" here. I could not find a way to make the background of the header transparent (when the header has rounded corners - there's a grey area). To be honest, I wanted to just make a scrollable sheet of my own, but I'm a little bit tight on time and have sooo much other stuff to do. 

As a practice, I've tried copy and pasting your code, and adjusting it to my needs - which works great for me. Until I make one of my own, it would be greatly appreciated if I can use the modified code. I'm new to using someone else's package to create something for myself (usually, I like to create everything myself) and I didn't want to infringe on any copyrights nor not name you guys as the source of original code (wasn't sure where I would need to state that). I didn't get a full grasp of what I should do with the APACHE License...

Please let me know what you guys think, and if you'd like to contact me via email - email me at sookim482.dev@gmail.com!

Thank you for the awesome package :)

**Comment by dbenitez-bcn** [comment]
You can get more information on #29
